# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10dae19b0d3529d19baa98da993a5606796b8d949a7720bb4b0253cebc8bcd73511b1dcfb5ed28abbfe507e0be27d5422cb9c8536cd397d2ef9eb0ac6d971980

test:
  secret_key_base: cb28d9ac22048573abdbdaddd4db87e5578b2fb19748241568cf3f4d7d24defff0f97fcfdc16bf7c2eb3abfeb3bb8ab9577f60c96dfed698a690ea3880e95c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
